### ISSUE TITLE
Evaluate the Code Deliverables

### ISSUE THREAD

**Issue by rogeruiz** [18F/usda-snap-pa#5]
_edit_ this issue was started a week prior to it being created.

## Acceptance Criteria

- [x] Have a working version of the Code Deliverables running locally
- [x] Document how to get Code Deliverables stood up
- [x] Evaluate Code Deliverables

## Base criteria for software evaluation

- understandability
- documentation
- buildability
- installability
- interoperability

## Evaluating the following codebases

- swim-alfresco-repo-uatrelease2.3.1/
- swim-alfresco-share-uatrelease2.3.1/
- swim-jq-uatrelease2.3.1/
- SWIM HTML Code Releases

**Comment by rogeruiz** [comment]
Those with access can view the document here: https://docs.google.com/document/d/13lUqC9_2YF6NuggtfXVpCw7W0_RvITWp1rPKvKTZCbw/edit#heading=h.5jj5fsv6qx58

**Comment by nikzei** [comment]
@rogeruiz, We've done a v1 pass at this - how about I move to done?
We can open a new card next sprint for v2 pass incorporating feedback from Michael?

**Comment by rogeruiz** [comment]
Yeah, I agree. sounds good!
